language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
  - develop
before_install:
- npm install -g bower
- npm install -g bless
- npm install -g requirejs
install: true
script: mvn package -P production

