language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
  - develop
before_install:
- npm install -g bower
- npm install -g bless
- npm install -g requirejs
before_script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P production
script: mvn package -P production

